# Generated by Django 2.0.4 on 2018-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(),
        ),
    ]
